import 'package:ar_flutter_plugin/utils/json_converters.dart';
import 'package:flutter/widgets.dart';

/// Object attached to a tracked physical entity of the AR environment (can be initialized with a world transformation)
class ARAnchor {
  ARAnchor({
    required this.transformation,
    String? name,
  }) : name = name ?? UniqueKey().toString();

  /// Determines the name of the [ARAnchor]
  /// Will be autogenerated if not defined.
  final String name;

  /// Defines the anchor’s rotation, translation and scale in world coordinates.
  final Matrix4 transformation;

  /// Constructs an [ARAnchor] from a serialized anchor object
  factory ARAnchor.fromJson(Map<String, dynamic> json) {
    return ARAnchor(
        transformation:
            const MatrixConverter().fromJson(json['transformation'] as List),
        name: json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'transformation': MatrixConverter().toJson(transformation),
      'name': name,
    };
  }
}
